import React from 'react';import{createRoot}from'react-dom/client';import'./index.css';
const PHONE='tel:+919626202662',WA='https://wa.me/919626202662',EMAIL='mailto:aaembroideryjob@gmail.com',MAP='https://www.google.com/maps/place/AA+Embroidery+works/data=!4m2!3m1!1s0x0:0xec70333c7d18f663?sa=X&ved=1t:2428&ictx=111',WEBSITE='https://www.aaworks.in/';
const HERO='https://ik.imagekit.io/MiCV/hero-embroidery-machine.png',LOGO='https://ik.imagekit.io/MiCV/Frame%2032.png';
const Icon=({children}:{children:React.ReactNode})=><span className="icon">{children}</span>;
function App(){const save=()=>{const v=['BEGIN:VCARD','VERSION:3.0','FN:AA Embroidery Works','ORG:AA Embroidery Works','TEL;TYPE=CELL:+919626202662','EMAIL:aaembroideryjob@gmail.com','URL:https://www.aaworks.in/','ADR;TYPE=WORK:;;7A, Kennady St, MG Nagar;Tharamani;Chennai;600113;India','NOTE:Custom Embroidery | DTF Print | Apparel | Personalised Gifts','END:VCARD'].join('\r\n');try{const f=new File([v],'AA-Embroidery-Works.vcf',{type:'text/vcard'});if(navigator.share&&navigator.canShare?.({files:[f]})){navigator.share({title:'AA Embroidery Works',files:[f]}).catch(()=>{});return}}catch{}const u=URL.createObjectURL(new Blob([v],{type:'text/vcard'})),a=document.createElement('a');a.href=u;a.download='AA-Embroidery-Works.vcf';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};return <div className="stage"><div className="card">
<header className="hero"><img className="hero-bg" src={HERO}/><div className="hero-shade"/><div className="hero-copy"><h1><em>Stitching</em><br/>Your Ideas<br/>to Life</h1><div className="rule"/><p>QUALITY IN EVERY STITCH</p></div><div className="hero-script">Quality<br/>in Every<br/>Stitch ♡</div><svg className="wave" viewBox="0 0 402 40" preserveAspectRatio="none"><path d="M0 40 Q201 0 402 40 L402 40 L0 40Z"/></svg></header>
<div className="logo-wrap"><img src={LOGO} className="logo"/><span className="status"/></div>
<main className="body"><section className="heading"><h2>AA Embroidery Works</h2><p>CUSTOM STITCHES FOR A BRIGHTER TOMORROW</p></section>
<section className="services"><div><Icon>✦</Icon><span>CUSTOM<br/>EMBROIDERY</span></div><div><Icon>▣</Icon><span>DTF PRINT</span></div><div><Icon>◇</Icon><span>APPAREL</span></div><div><Icon>✧</Icon><span>PERSONALISED<br/>GIFTS</span></div></section>
<p className="desc">We turn your ideas into beautiful stitches. Premium embroidery,<br/>DTF print, apparel and custom solutions for every occasion.</p>
<section className="contacts"><a href={PHONE}><Icon>☎</Icon><span><b>9626202662</b><small>Call / WhatsApp</small></span><i>›</i></a><a href={EMAIL}><Icon>✉</Icon><span><b>aaembroideryjob@gmail.com</b><small>Email Us</small></span><i>›</i></a><a href={MAP} target="_blank" rel="noreferrer"><Icon>⌖</Icon><span><b>7A, Kennady St, MG Nagar, Tharamani,<br/>Chennai - 600113</b><small>Get Directions</small></span><i>›</i></a></section>
<div className="socials"><a href={WA} aria-label="WhatsApp">WA</a><a href="#" onClick={e=>e.preventDefault()} aria-label="Instagram">IG</a><a href="#" onClick={e=>e.preventDefault()} aria-label="Facebook">f</a><a href={WEBSITE} target="_blank" rel="noreferrer" aria-label="Website">⌂</a></div>
<div className="save-slot"><button onClick={save}><span>♙+</span><b>Save to Contacts</b><span>›</span></button></div>
<footer><span/> <div>LET'S STAY CONNECTED<br/><b>AA EMBROIDERY WORKS</b></div> <span/></footer></main></div></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);